/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE map_infoBaseService PLEASE EDIT ../map_info.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Map_info } from '../../domain/mapworkrs_db/map_info';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../map_info.service.ts
 */

/*
 * SCHEMA DB map_info
 *
	{
		c_lang: {
			type: 'String'
		},
		c_long: {
			type: 'String'
		},
		cre_date: {
			type: 'Date'
		},
		cre_user: {
			type: 'String'
		},
		e_lang: {
			type: 'String'
		},
		e_long: {
			type: 'String'
		},
		map_base: {
			type: 'String'
		},
		map_bld_co: {
			type: 'String'
		},
		map_dist: {
			type: 'String'
		},
		map_input_date: {
			type: 'Date'
		},
		map_memo: {
			type: 'String'
		},
		map_name: {
			type: 'String'
		},
		map_sppy_user: {
			type: 'String'
		},
		mapid: {
			type: 'String'
		},
		mobile_table: {
			type: 'String'
		},
		s_lang: {
			type: 'String'
		},
		s_long: {
			type: 'String'
		},
		url: {
			type: 'String'
		},
		ver: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		mar_rel: {
			type: Schema.ObjectId,
			ref : "map_info"
		},
	}
 *
 */
@Injectable()
export class Map_infoBaseService {

    contextUrl: string = environment.endpoint + '/map_info';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * map_infoService.create
    *   @description CRUD ACTION create
    *   @param map_info obj Object to insert
    *
    */
    create(item: Map_info): Observable<Map_info> {
        return this.http
            .post<Map_info>(this.contextUrl, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
