/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE map_detailBaseService PLEASE EDIT ../map_detail.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Map_detail } from '../../domain/mapworkrs_db/map_detail';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../map_detail.service.ts
 */

/*
 * SCHEMA DB map_detail
 *
	{
		add_layer1: {
			type: 'String'
		},
		add_layer2: {
			type: 'String'
		},
		add_layer3: {
			type: 'String'
		},
		base_file: {
			type: 'String'
		},
		base_map: {
			type: 'String'
		},
		input_user: {
			type: 'String'
		},
		map_box: {
			type: 'String'
		},
		map_id: {
			type: 'String'
		},
		map_line: {
			type: 'String'
		},
		map_name: {
			type: 'String'
		},
		map_txt: {
			type: 'String'
		},
		map_type: {
			type: 'String'
		},
		update_date: {
			type: 'Date'
		},
		update_res: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		mar_rel: {
			type: Schema.ObjectId,
			ref : "map_info"
		},
	}
 *
 */
@Injectable()
export class Map_detailBaseService {

    contextUrl: string = environment.endpoint + '/map_detail';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS


    // Custom APIs

}
