/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE map_detailBase PLEASE EDIT ../map_detail.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */

/**
 * This is the model of map_detail object
 *
 */
export class Map_detailBase {

    constructor() { }

    public _id: string;
    public add_layer1?: string;
    public add_layer2?: string;
    public add_layer3?: string;
    public base_file?: string;
    public base_map?: string;
    public input_user?: string;
    public map_box?: string;
    public map_id?: string;
    public map_line?: string;
    public map_name?: string;
    public map_txt?: string;
    public map_type?: string;
    public update_date?: Date;
    public update_res?: string;
}
