/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE map_infoBase PLEASE EDIT ../map_info.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Map_detail } from '../map_detail';

/**
 * This is the model of map_info object
 *
 */
export class Map_infoBase {

    constructor() { }

    public _id: string;
    public c_lang?: string;
    public c_long?: string;
    public cre_date?: Date;
    public cre_user?: string;
    public e_lang?: string;
    public e_long?: string;
    public map_base?: string;
    public map_bld_co?: string;
    public map_dist?: string;
    public map_input_date?: Date;
    public map_memo?: string;
    public map_name?: string;
    public map_sppy_user?: string;
    public mapid?: string;
    public mobile_table?: string;
    public s_lang?: string;
    public s_long?: string;
    public url?: string;
    public ver?: string;
    // Relations mar_rel
    public mar_rel: Map_detail | string;
}
